commerce/carts/urls.py
from django.conf.urls import url
from carts import views 


urlpatterns = [
	url(r'^$', views.CartView.as_view(), name="cart"),
    url(r'^count/$', views.ItemCounView.as_view(), name="cart_item_count"),
    url(r'^checkout/$', views.CheckOutView.as_view(), name="checkout"),
    url(r'^final/$', views.CheckoutFinalView.as_view(), name="final_checkout"),
    url(r'^contact/$', views.contact, name="contact"),
]

commerce/commerce/urls.py
# from django.conf import settings
from django.conf.urls import url, include
# from django.conf.urls.static import static
from django.contrib import admin
from product import urls as product
from product import url_categories as categories
from carts import urls as carts
from order import urls as order
from website import urls as website

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls', app_name="product", namespace="product")),
    url(r'^categories/', include('product.url_categories', app_name="categories", namespace="categories")),
    url(r'^cart/', include('carts.urls', app_name="carts", namespace="carts")),
    url(r'^order/', include('order.urls', app_name="order", namespace="order")),
    url(r'^web/', include('website.urls', app_name="website", namespace="website")),
]

commerce/order/urls.py
from django.conf.urls import url
from order import views 


urlpatterns = [
	url(r'^address/$', views.AddressSelectedFormView.as_view(), name="checkout_address"),
    url(r'^address/add/$', views.UserAddressCreateView.as_view(), name="create_address"),
    url(r'^list/$', views.OrderListView.as_view(), name="order_list"),
    url(r'^(?P<pk>\d+)/$', views.OrderDetalView.as_view(), name="order_detail"),
]

commerce/carts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from product.models import Variations
from django.db.models.signals import  pre_save, post_save, post_delete
from decimal import Decimal



'''
Incase the buyer wants to by several variations of the same product
Need to use two ForeignKey if using through=CartItem,
"Cart" has to be in quotes because class Cart defined after CartItem
'''
class CartItem(models.Model):
	cart = models.ForeignKey("Cart")
	item = models.ForeignKey(Variations)
	quantity = models.PositiveIntegerField(default=1)
	line_item_total = models.DecimalField(max_digits=10, decimal_places=2,null=True,)


	def __str__(self):
		return self.item.title

	'''
	Romove method for the cart to remove items,
	creates a link to remove an item
	'''
	def remove(self):
		return "{}?item={}&delete=True".format(reverse("carts:cart"), self.item.id)

	'''
	Getting title from model to display in the Cart
	'''
	def get_title(self):
		return "{}   {}".format(self.item.product.title, self.item.title)

'''
Setting the line_item_total through pre save signal
'''
def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
	qty =instance.quantity
	if int(qty) >= 1:
		price = instance.item.get_price()
		line_item_total = Decimal(qty) * Decimal(price)
		instance.line_item_total = line_item_total

pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)

'''
Happaning after the item has been saved into db
'''
def cart_itemm_post_save_receiver(sender, instance, *args, **kwargs):
	instance.cart.update_subtotal()

post_save.connect(cart_itemm_post_save_receiver, sender = CartItem)

post_delete.connect(cart_itemm_post_save_receiver, sender = CartItem)



'''
Cart is based on Variations, all products/items in the cart = Variations
Althogh the queryset is Variations it would use CartItem as an intermediary
'''
class Cart(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
	items = models.ManyToManyField(Variations, through=CartItem)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	subtotal = models.DecimalField(max_digits=20, decimal_places=2,default=1)
	tax_percentage = models.DecimalField(max_digits=20, decimal_places=5, default=0.085)
	tax_total = models.DecimalField(max_digits=20, decimal_places=2,null=True,default=1)
	total = models.DecimalField(max_digits=20, decimal_places=2,null=True,default=1)

	def __str__(self):
		return str(self.id)

	'''
	Updating sub_total
	'''
	def update_subtotal(self):
		subtotal = 0
		items = self.cartitem_set.all()
		for item in items:
			subtotal += item.line_item_total
		self.subtotal = "{:10.2f}".format(subtotal)
		self.save()


'''
Saving taxes and total
'''
def do_tax_and_total_receiver(sender, instance, *args, **kwargs):
	subtotal = Decimal(instance.subtotal)
	tax_total = round(subtotal * Decimal(instance.tax_percentage), 2) #8.5%
	total = round(subtotal + Decimal(tax_total), 2)
	instance.tax_total = "{:10.2f}".format(tax_total)
	instance.total = "{:10.2f}".format(total)

pre_save.connect(do_tax_and_total_receiver, sender=Cart)

commerce/carts/forms.py
from django import forms

class ContactForm(forms.Form):
	full_name = forms.CharField(max_length=120, )
	email = forms.EmailField(max_length=120, )
	message = forms.CharField(max_length=120, )

commerce/carts/views.py
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.views.generic.detail import SingleObjectMixin, DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.base import View
from product.models import Variations
from carts.models import Cart, CartItem
from django.contrib.auth.forms import AuthenticationForm
from order.mixins import CartOrderMixin
from order.models import UserCheckout, Order, UserAddress
from order.forms import GuestCheckoutForm
from .forms import ContactForm

def contact(request):
	form = ContactForm(request.POST or None)
	if form.is_valid():
		email = form.cleaned_data.get("email")
		message = form.cleaned_data.get("message")
		full_name = form.cleaned_data.get("full_name")
		subject = "HUY"
		from_email = settings.EMAIL_HOST_USER
		to_email = ["artyudin@outlook.com"]
		contact_message = "Full name: {},Emal: {},Message: {}".format(full_name,email,message)
		send_mail(
    		subject,
    		contact_message,
    		from_email,
    		to_email,
    		fail_silently=False,
		)

	context = {
			"form":form,

	}
	return render(request, "carts/contact.html", context)






'''
Importing braintree
'''
import braintree 

if settings.DEBUG:
	braintree.Configuration.configure(braintree.Environment.Sandbox,
		merchant_id=settings.BRAINTREE_MERCHAND_ID,
		public_key=settings.BRAINTREE_PUBLIC,
		private_key=settings.BRAINTREE_PRIVATE)


'''
View to get cart count number by cart-count-badge
'''
class ItemCounView(View):

	def get(self, request, *args, **kwargs):

		if request.is_ajax():
			cart_id = self.request.session.get("cart_id")
			if cart_id == None:
				count = 0
			else:
				cart = Cart.objects.get(id=cart_id)
				count = cart.items.count()
			request.session["cart_item_count"] = count
			return JsonResponse({"count":count})
		else:
			raise HttpResponseRedirect


'''
Cart is binded to session, if cart does not exist, we create 
new cart and bind it the session, session would expire in
set_expiry(300) = 5 min or if (0) when browser closed,
if user is_authenticated then cart would be bined to user  
'''
class CartView(SingleObjectMixin, View):
	model = Cart
	template_name = "carts/cart.html"

	'''
	Checking if cart exists, if not creating a Cart
	'''
	def get_object(self, *args, **kwargs):
		self.request.session.set_expiry(0)
		cart_id = self.request.session.get("cart_id")
		if cart_id == None:
			cart = Cart()
			# self.request.user.get_tax_percentage()
			# cart.tax_percentage = 0.075
			cart.save()
			cart_id = cart.id
			self.request.session["cart_id"] = cart_id
		cart = Cart.objects.get(id=cart_id)
		if self.request.user.is_authenticated():
			cart.user = self.request.user
			cart.save()
		return cart

	'''
	Adding item to a cart
	'''
	def get(self, request, *args, **kwargs):
		cart =self.get_object()
		item_id = request.GET.get("item")
		delete_item = request.GET.get("delete", False)
		item_added = False
		if item_id:
			item_instance = get_object_or_404(Variations, id=item_id)
			qty = request.GET.get("qty", 1)
			try:
				if int(qty) < 1:
					delete_item = True
			except:
				raise Http404
			cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item_instance)
			if created:
				item_added = True
			if delete_item:
				cart_item.delete()
			else:
				cart_item.quantity = qty
				cart_item.save()
			if not request.is_ajax():
				return HttpResponseRedirect(reverse("carts:cart"))

		if request.is_ajax():
			try:
				total = cart_item.line_item_total
			except:
				total = None
			try:
				subtotal = cart_item.cart.subtotal
			except:
				subtotal = None
			try:
				cart_total = cart_item.cart.total
			except:
				cart_total = None
			try:
				tax_total = cart_item.cart.tax_total
			except:
				tax_total = None
			try:
				total_items = cart_item.cart.items.count()
			except:
				total_items = 0

			data = {
					"deleted":delete_item, 
					"item_added": item_added,
					"line_total": total,
					"subtotal": subtotal,
					"cart_total": cart_total,
					"tax_total": tax_total,
					"total_items":total_items,
					}

			return JsonResponse(data)
		context = {
			"object":self.get_object()
		}
		template = self.template_name

		return render(request, template, context)





'''
Checking out process
'''
class CheckOutView(CartOrderMixin, FormMixin, DetailView):
	model = Cart
	template_name = "carts/checkout.html"
	form_class = GuestCheckoutForm

	def get_object(self, *args, **kwargs):
		cart = self.get_cart()
		if cart == None:
			return None
		return cart

	'''
	Allowing checking out for non registered users
	'''
	def get_context_data(self, *args, **kwargs):
		context = super(CheckOutView, self).get_context_data(*args, **kwargs)
		user_can_continue = False
		user_check_id = self.request.session.get("user_checkout_id")

		if self.request.user.is_authenticated():
			user_can_continue = True
			user_checkout, created = UserCheckout.objects.get_or_create(email=self.request.user.email)
			user_checkout.user = self.request.user
			user_checkout.save()
			context["client_token"] = user_checkout.get_client_token() 
			self.request.session["user_checkout_id"] = user_checkout.id
		elif not self.request.user.is_authenticated() and user_check_id == None:
			context["login_form"] = AuthenticationForm()
			context["next_url"] = self.request.build_absolute_uri()
		else:
			pass

		if user_check_id != None:
			user_can_continue = True
			if not self.request.user.is_authenticated(): #guest user
				user_checkout_2 = UserCheckout.objects.get(id=user_check_id)
				context["client_token"] = user_checkout_2.get_client_token()

		context["order"] = self.get_order()
		context["user_can_continue"] = user_can_continue
		context["form"] = self.get_form()
		return context 

	'''
	Getting email from unregistered users
	'''
	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		form = self.get_form()
		if form.is_valid():
			email = form.cleaned_data.get("email")
			user_checkout, created = UserCheckout.objects.get_or_create(email=email)
			request.session["user_checkout_id"] = user_checkout.id
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	'''
	If we get email successfuly we redirect to the same checkout
	'''
	def get_success_url(self):
		return reverse("order:checkout_address")

	'''
	Creating new order,
	by obtaining session id
	'''
	def get(self, request, *args, **kwargs):
		get_data = super(CheckOutView, self).get(request, *args, **kwargs)
		cart = self.get_object()
		if cart == None:
			return redirect("carts:cart")
		new_order = self.get_order()
		user_checkout_id = request.session.get("user_checkout_id")
		if user_checkout_id != None:
			user_checkout = UserCheckout.objects.get(id=user_checkout_id)
			if new_order.billing_address_id == None or new_order.shipping_address_id == None:
				return redirect("order:checkout_address")

			new_order.user = user_checkout
			new_order.save()
		return get_data


'''
Finalizing checkout,
obtaining payment_method_nonce from checkout.html,
for braintree
'''
class CheckoutFinalView(CartOrderMixin, View):

	def post(self, request, *args, **kwargs):
		order = self.get_order()
		order_total = order.order_total
		nonce = request.POST.get("payment_method_nonce")
		if nonce:
			result = braintree.Transaction.sale({
				"amount": order_total,
				"payment_method_nonce": nonce,
				"billing": {
					"postal_code": "{}".format(order.billing_address.zip_code),
			  	},
				"options": {
					"submit_for_settlement": True
				}
			})
			if result.is_success:
				order.mark_completed(order_id = result.transaction.id)
				messages.success(request, "Thank you for your order.")
				del request.session["cart_id"]
				del request.session["order_id"]
			else:
				messages.success(request, "{}".format(result.message))
				return redirect("carts:checkout")

		return redirect("order:order_detail", pk=order.pk)

	def get(self, request, *args, **kwargs):
		return redirect("carts:checkout")

commerce/carts/templates/carts/alert.html
<div class='container-alert-flash'><div class='alert alert-success alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>{{ message }}</div></div>

commerce/carts/templates/carts/cart.html
{% extends "product/base.html" %}

<script>
{% block jquery %}
	function showFlashMessage(message){
		var template = "{% include "carts/alert.html" with message='" + message + "' %}"
			$("body").append(template);
			$(".container-alert-flash").fadeIn();
			setTimeout(function(){
				$(".container-alert-flash").fadeOut();
			}, 2500);


	}
$(".item-qty").change(function(){
	// $(this).next(".btn-update").fadeIn();
	// event.preventDefault();
	var item = $(this).prev("input[type='hidden']").val();
	var qty = $(this).val();
	var data = {
		item:item,
		qty:qty

	}
	$.ajax({
		type:"GET",
		url:"{% url 'carts:cart' %}",
		data: data,
		success: function(data){
			$("#jquery-message").text("Added" + data.item_added + "Deleted" + data.deleted)
			if (data.deleted){
				$("#item-"+item).fadeOut();
				$("#subtotal").text(data.subtotal);
				$("#tax_total").text(data.tax_total);
				$("#cart_total").text(data.cart_total);
				
			} else{
				$("#item-line-total-"+item).text(data.line_total);
				$("#subtotal").text(data.subtotal);
				$("#tax_total").text(data.tax_total);
				$("#cart_total").text(data.cart_total);
			}

			if (data.total_items == 0){
				$(".table").fadeOut()
				showFlashMessage("Your cart is empty")

			}

			var message = ""
			if (data.item_added){
				message = "New item added"
			} else if (data.deleted){
				message = "item removed"
			} else{
				message = "Item updated"
			}
			showFlashMessage(message);
			updateCartItemCount();
		},
		error:function(response, error){
			$("#add-form").submit()
		},

	});

});

{% endblock %}
</script>




{% block content %}


{% if object.cartitem_set.count < 1 %}

<h1>Your cart is empty</h1>

{% else %}

<table class="table">

{% for item in object.cartitem_set.all %}

<tr id="item-{{ item.item.id }}">
	
	<td>{{ item.get_title }}</td>
	<td><form action"." method="GET"><input type="hidden" name="item" value="{{ item.item.id }}"/><input type="number" class="item-qty" name="qty" value="{{ item.quantity }}"/><input type="submit" class="btn-update btn btn-link" value="Update item" style="display:none;"/></form></td>
	<td id="item-line-total-{{ item.item.id }}">{{ item.line_item_total }}</td>
	<td></td>
	<td><a href="{{ item.remove }}">Remove</a></td>
	
</tr>
{% endfor %}
<tr>
	<td  colspan="4" class="text-right">Subtotal:<span id="subtotal">{{ object.subtotal}}</span></td>
</tr>
<tr>
	<td  colspan="4" class="text-right">Tax:<span id="tax_total">{{ object.tax_total}}</span></td>
</tr>
<tr>
	<td  colspan="4" class="text-right">Total:<span id="cart_total">{{ object.cart_total}}</span></td>
</tr>
<tr>
	<td  colspan="4" class="text-right"><a href="{% url 'carts:checkout' %}">Checkout</a></td>
</tr>
</table>
{% endif %}
{% endblock %}

commerce/carts/templates/carts/checkout.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

<script>
{% block jquery %}
var clientToken = "{{ client_token}}";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});

{% endblock %}
</script>


{% block content %}




{% if not user_can_continue %}

<div class="col-sm-6">
<h3>Continue as Guest</h3>
<form method="POST" action="">
{% csrf_token %}
{{ form|crispy }}
<input class="btn" type="submit" name="" value="Continue as Guest"/>
</form>
</div>

<div class="col-sm-6">
<p class="lead"> Login to Continue</p>
<form method="POST" action="#ADD LOGIN URL">
{% csrf_token %}

{{ login_form|crispy }}
<input type="hidden" name="next" value="{{ next_url }}"/>
<input class="btn" type="submit" name="" value="Login"/>
</form>
</div>

{% else %}
<div class='col-sm-4 col-sm-offset-4 text-center'>
<p class="lead">Your order</p>
{% include "order/order_summary_short.html" with order=order %}
<table class="table">
<tr><td>Item(s){{ order.cart.cartitem_set.count }}
Cart Items: 
<ul>{% for item in order.cart.cartitem_set.all %}
<ul>{{ item.get_title }}</ul>
{% endfor %}</ul></td></tr>
<tr><td>Cart Subtotal: {{ order.cart.subtotal }}</td></tr>
<tr><td>Tax: {{ order.cart.tax_total }}</td></tr>
<tr><td>Items Total: {{ order.cart.total }}</td></tr>
<tr><td>Shipping: {{ order.shipping_total_price }}</td></tr>
<tr><td>Order Total: {{ order.order_total }}</td></tr>
</table>
</div>

<div class='col-sm-4 col-sm-offset-4 text-center'>
<p class="lead"><b>Billing address:</b></p><br/>
{{ order.billing_address.get_address }}

</div>
<p class="lead"><b>Shipping to:</b></p><br/>
{{ order.shipping_address.get_address }}
<p><a href="{% url 'order:checkout_address' %}">Change an address</a></p>
<p><a href="{% url 'order:create_address' %}">Add an address</a></p>



<form id="checkout" method="POST" action="{% url 'carts:final_checkout' %}">
{% csrf_token %}

<!-- <input type="hidden" name="payment_token" value="ABC"/> -->
  <div id="payment-form"></div>
<p><b><button type="submit">Complete order</button></b></p>
</form>


</div>

{% endif %}


{% endblock %}