commerce/carts/urls.py
from django.conf.urls import url
from carts import views 


urlpatterns = [
	url(r'^$', views.CartView.as_view(), name="cart"),
    url(r'^count/$', views.ItemCounView.as_view(), name="cart_item_count"),
    url(r'^checkout/$', views.CheckOutView.as_view(), name="checkout"),
    url(r'^final/$', views.CheckoutFinalView.as_view(), name="final_checkout"),
    url(r'^contact/$', views.contact, name="contact"),
]

commerce/commerce/urls.py
# from django.conf import settings
from django.conf.urls import url, include
# from django.conf.urls.static import static
from django.contrib import admin
from product import urls as product
from product import url_categories as categories
from carts import urls as carts
from order import urls as order
from website import urls as website

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls', app_name="product", namespace="product")),
    url(r'^categories/', include('product.url_categories', app_name="categories", namespace="categories")),
    url(r'^cart/', include('carts.urls', app_name="carts", namespace="carts")),
    url(r'^order/', include('order.urls', app_name="order", namespace="order")),
    url(r'^web/', include('website.urls', app_name="website", namespace="website")),
]

commerce/product/urls.py
from django.conf.urls import url
from product import views 


urlpatterns = [
	url(r'^$', views.ProductListView.as_view(), name="product_list"),
    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product_detail"),
    url(r'^(?P<pk>\d+)/inventory/$', views.VariationsListView.as_view(), name="product_inventory"),
    url(r'^front/$', views.FrontPageView.as_view(), name="front_page"),
]

commerce/product/models.py
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.db import models


class ProductQuerySet(models.query.QuerySet):

	def active(self):
		return self.filter(active=True)

'''
Customizing Product.objects
'''
class ProductManager(models.Manager):

	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	'''
	overwriting get_quryset setting active=True
	customizing Product.objects.all()
	insted of Product.objects.filter(active=False)
	'''
	def all(self, *args, **kwargs):
		return self.get_queryset().active()

	'''
	Getting related products, writing special queryset method
	Customizing model manager to get related products from all
	and products as default one, exclude current shown displayed product
	'''
	def get_related(self, instance):
		products_group_one = self.get_queryset().filter(categories__in=instance.categories.all())
		products_group_two = self.get_queryset().filter(default=instance.default)
		qs = (products_group_one | products_group_two).exclude(id=instance.id).distinct()
		return qs


 

class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	price = models.DecimalField(decimal_places=2, max_digits=20)
	active = models.BooleanField(default=True)
	categories = models.ManyToManyField('Category', blank=True)
	default = models.ForeignKey('Category', related_name='default_category', null=True, blank=True)

	objects = ProductManager()


	def __str__(self):
		return self.title

	'''
	Creating urls to Product detail 
	'''
	def get_absolute_url(self):
		return reverse("product:product_detail", kwargs={"pk":self.pk})

	'''
	Getting imgs product and for related products
	'''
	def get_image_url(self):
		img =self.productimage_set.first()
		if img:
			return img.image.url
		return img


class Variations(models.Model):
	product = models.ForeignKey(Product)
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	price = models.DecimalField(decimal_places=2, max_digits=20)
	sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
	active = models.BooleanField(default=True)
	inventory = models.IntegerField(null=True, blank=True)

	def __str__(self):
		return self.title

	def get_price(self):
		if self.sale_price is not None:
			return self.sale_price
		else:
			return self.price

	def get_absolute_url(self):
		return self.product.get_absolute_url()
	'''
	Creating a link to add item/Variation to cart
	'''
	def add_to_cart(self):
		return "{}?item={}&qty=1".format(reverse("carts:cart"), self.id)
	'''
	Creating a link to remove item/Variation to cart
	'''
	# def remove_to_cart(self):
	# 	return "{}?item={}&qty=1".format(reverse("carts:cart"), self.id)

'''
Checking if Product has variations if not will set default
Basket takes variations
'''
def product_post_saved_receiver(sender, instance, created, *args, **kwargs):
	
	product = instance
	variations = product.variations_set.all()
	if variations.count() == 0:
		new_variation = Variations()
		new_variation.product = product
		new_variation.title = "Default"
		new_variation.price = product.price
		new_variation.save()



post_save.connect(product_post_saved_receiver, sender=Product)

# '''
# Changing file img name to one according product
# '''
# def image_upload_to(instance, filename):
# 	title = instance.product.title
# 	slug = slugify(title)
# 	basename, file_extension = filename.split(".")
# 	new_filename = "%s-%s-%s" %(slug, instance.id, file_extension)
# 	return "products/%s/%s" %(slug, new_filename)


class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to='product/static/product/pics')

	def __str__(self):
		return self.product.title



class Category(models.Model):
	title = models.CharField(max_length=120, unique=True)
	slug = models.SlugField(unique=True)
	description = models.TextField(blank=True, null=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('categories:category_detail', kwargs={"slug":self.slug})

'''
Changing file img name to one according ProductFeatured
upload_to=image_upload_to_featured
'''
def image_upload_to_featured(instance, filename):
	title = instance.prduct.title
	slug = slugify(title)
	basename, file_extension = filename.split(".")
	new_filename = "%s-%s-%s" %(slug, instance.id, file_extension)
	return "products/%s/%s" %(slug, new_filename)

class ProductFeatured(models.Model):
	prduct = models.ForeignKey(Product)
	image = models.ImageField(upload_to=image_upload_to_featured, blank=True)
	title = models.CharField(max_length=120, blank=True, null=True)
	text = models.TextField(max_length=120, blank=True, null=True)
	text_on_right_side = models.BooleanField(default=False)
	show_price = models.BooleanField(default=False)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.prduct.title

commerce/product/forms.py
from django import forms
from django.forms.models import modelformset_factory

from.models import Variations



class VariationsInventoryForm(forms.ModelForm):
	class Meta:
		model = Variations
		fields = [
			"title",
			"price",
			"sale_price",
			"inventory",
			"active",
		]

VariationsInventoryFormSet = modelformset_factory(Variations, form=VariationsInventoryForm, extra=1)

commerce/product/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Product, Variations, Category, ProductFeatured
from .forms import VariationsInventoryFormSet
from .mixins import StaffRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.utils import timezone

'''
Updating inventory for Product Variations through variations_list.html
using VariationsInventoryFormSet plus two additional empty forms 
'''
class VariationsListView(StaffRequiredMixin, ListView):
	model = Variations
	queryset = Variations.objects.all()

	'''
	Rendering Form
	'''
	def get_context_data(self, *args, **kwargs):
		context = super(VariationsListView, self).get_context_data(*args, **kwargs)
		context["formset"] = VariationsInventoryFormSet(queryset=self.get_queryset())
		return context 

	'''
	Obtaining variations for a particular product based on a pruduct pk
	out of all Variations
	'''
	def get_queryset(self, *args, **kwargs):

		product_pk = self.kwargs.get("pk")
		if product_pk:
			product = get_object_or_404(Product, pk=product_pk)
			queryset = Variations.objects.filter(product=product)
		return queryset

	'''
	This POST method can handle FILES
	Messages alert user when something has been done in the system
	'''
	def post(self, request, *args, **kwargs):
		formset = VariationsInventoryFormSet(request.POST, request.FILES)
		if formset.is_valid():
			formset.save(commit=False)
			for form in formset:
				new_item = form.save(commit=False)
				if new_item.title:
					product_pk = self.kwargs.get("pk")
					product = get_object_or_404(Product, pk=product_pk)
					new_item.product = product
					new_item.save()
			messages.success(request, "Your inventory updated")
			return redirect("product:product_list")
		
		raise Http404







'''
Returns specific list of products
'''
class ProductListView(ListView):
	model = Product

	def get_context_data(self, *args, **kwargs):
		# overwriting original context to maipulate context
		# getting default content by super
		context = super(ProductListView, self).get_context_data(*args, **kwargs)
		# customize context by adding attributes to context
		context["now"] = timezone.now()
		context["query"] = self.request.GET.get("q")
		return context 

	'''
	Overwriting query search to make site searchable
	pay attention on _ _icontains
	for more precise search create qs2
	distinct() makes sure that we recieve anly one object 
	'''
	def get_queryset(self, *args, **kwargs):
		qs = super(ProductListView, self).get_queryset(*args, **kwargs)
		query = self.request.GET.get("q")
		if query:
			qs = self.model.objects.filter(
				Q(title__icontains=query) |
				Q(description__icontains=query)
				)
			try:
				qs2 = self.model.objects.filter(
					Q(price=query)
				)
				qs = (qs | qs2).distinct()
			except:
				pass
		return qs



'''
Returns specific product details
can be customized
template_name = 'product/product_detail.html'
'''
class ProductDetailView(DetailView):
	model = Product

	'''
	Method to get related products out of Model manager
	get_related(), can be ordered and show only number of related products, 
	can be ordered and show only number of related products
	order is managed by lambda function
	'''
	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		instance = self.get_object()
		context["related"] = sorted(Product.objects.get_related(instance)[:5], key=lambda x: x.title)
		return context




'''
List view for categories
'''
class CategoryListView(ListView):
	model = Category
	queryset = Category.objects.all()
	template_name = 'product/product_list.html'

'''
Category detail view
'''
class CategoryDetailView(DetailView):
	model= Category

	'''
	Setting how query would come 
	'''
	def get_context_data(self, *args, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
		obj =self.get_object()
		product_set = obj.product_set.all()
		default_products = obj.default_category.all()
		products = ( product_set | default_products).distinct()
		context["products"] = products
		return context 

class FrontPageView(View):
	template_name = "product/base.html"
	# model = ClientIncome
	# form_class = ClientIncomeForm
	context = None

	def get(self, request):
		featured_product = ProductFeatured.objects.first()
		# if self.model.objects.filter(user=request.user).exists():
		# 	return render(request, 'dashboard.html')
		# else:
		self.context = {"featured_product":featured_product}

		return render(request, self.template_name, self.context)

commerce/product/templates/product/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>REEN</title>
    
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'website/assets/css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Customizable CSS -->
    <link href="{% static 'website/assets/css/main.css' %}" rel="stylesheet" data-skrollr-stylesheet>
    <link href="{% static 'website/assets/css/orange.css' %}" rel="stylesheet" title="Color">
    <link href="{% static 'website/assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'website/assets/css/owl.transitions.css' %}" rel="stylesheet">
    <link href="{% static 'website/assets/css/animate.min.css' %}" rel="stylesheet">
    
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">
    
    <!-- Icons/Glyphs -->
    <link href="{% static 'website/assets/fonts/fontello.css' %}" rel="stylesheet">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">
  </head>
  
<body>
{% include "__menu.html" %}

    <!-- ============================================================= MAIN ============================================================= -->
    
<main>

{% block content %}
{% endblock %}



</main>
    
    <!-- ============================================================= MAIN : END ============================================================= -->
{% include "__footer.html" %}
{% include "product/jscript.html" %}
<script>
$(document).ready(function(){
  {% block jquery %}

  {% endblock %}

});
</script>

</body>

</html>

commerce/product/templates/product/category_detail.html
{% extends "product/base.html" %}

{% block content %}
<h3>{{ object }}</h3>

<table class="table">

{% for product in products %}
<tr>
<td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
</tr>

{% endfor %}



</table>

{% endblock %}

commerce/product/templates/product/jscript.html
{% load staticfiles %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://js.braintreegateway.com/js/braintree-2.28.0.min.js"></script>
<script href="{% static 'product/alerts.js' %}" type="text/javascript" ></script>
<!-- JavaScripts for website -->
<!-- <script src="{% static 'website/assets/js/jquery.min.js' %}"></script> -->
<script src="{% static 'website/assets/js/jquery.easing.1.3.min.js' %}"></script>
<script src="{% static 'website/assets/js/jquery.form.js' %}"></script>
<script src="{% static 'website/assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'website/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'website/assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'website/assets/js/skrollr.min.js' %}"></script>
<script src="{% static 'website/assets/js/skrollr.stylesheets.min.js' %}"></script>
<script src="{% static 'website/assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'website/assets/js/waypoints-sticky.min.js' %}"></script>
<script src="{% static 'website/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'website/assets/js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'website/assets/js/jquery.easytabs.min.js' %}"></script>
<script src="{% static 'website/assets/js/google.maps.api.v3.js' %}"></script>
<script src="{% static 'website/assets/js/viewport-units-buggyfill.js' %}"></script>
<script src="{% static 'website/assets/js/scripts.js' %}"></script>

<!-- producT -->
<!-- Dropdown menu -->
<script src="{% static 'website/product/js/ddlevelsmenu.js' %}"></script> 
<!-- Countdown -->
<script src="{% static 'website/product/js/jquery.plugin.min.js' %}"></script> 
<script src="{% static 'website/product/js/jquery.countdown.min.js' %}"></script>    
<!-- jQuery Navco -->
<script src="{% static 'website/product/js/jquery.navgoco.min.js' %}"></script>
<!-- Filter for support page -->
<script src="{% static 'website/product/js/filter.js' %}"></script>         
<!-- Respond JS for IE8 -->
<script src="{% static 'website/product/js/respond.min.js' %}"></script>
<!-- HTML5 Support for IE -->
<script src="{% static 'website/product/js/html5shiv.js' %}"></script>
<!-- Custom JS -->
<script src="{% static 'website/product/js/custom.js' %}"></script>

<script>

function updateCartItemCount(){
	var badge = $("#cart-count-badge");

	$.ajax({
		type:"GET",
		url:"{% url 'carts:cart_item_count' %}",
		success: function(data){
			badge.text(data.count);
		},

	})


}



$(document).ready(function(){
	updateCartItemCount()
	
})

</script>

commerce/product/templates/product/product_list.html
{% extends "product/base.html" %}


{% block content %}
<!-- ============================================================= SECTION – PRICING TABLES ============================================================= -->
			
			<section id="pricing-tables">
				<div class="container inner">
					
					<div class="row">
						<div class="col-md-8 col-sm-9 center-block text-center">
							<header>
								<h1>Simple pricing, no surprises</h1>
								<p>In order to simplify the process, we have created Packages that will get you started right away.  If you can’t find the package that suits your needs, email us for a custom solution:
								</p>
							</header>
						</div><!-- /.col -->
					</div><!-- /.row -->
					
					<div class="row pricing col-4">
					{% for object in object_list %}
						
						<div class="col-lg-3 col-sm-6 inner-top-sm">
							<div class="plan">
								
								<header>
									<h2>{{ object.title }}</h2>
									
									<div class="price">
										<span class="currency">$</span>
										<span class="amount">499</span>
										<span class="period">/Month</span>
									</div><!-- /.price -->
									
									<a  href='{{ object.get_absolute_url }}' class="btn">Learn more</a>
								</header>
								
								<ul class="features">
									<li><i class="icon-picture-1"></i>Custom artwork design </li>
									<li><i class="icon-picture"></i>4 full comp designs</li>
									<li><i class="icon-scissors"></i>Unlimited revisions </li>
									<li><i class="icon-vcard"></i>Company stationary</li>
									<li><i class="icon-install"></i>Digital delivery</li>
								</ul><!-- /.features -->
								
							</div><!-- /.plan -->
						</div><!-- /.col -->	
				{% endfor %}
					</div><!-- /.row -->
					
				</div><!-- /.container -->
			</section>
			
			<!-- ============================================================= SECTION – PRICING TABLES : END ============================================================= -->




{% endblock %}

commerce/product/templates/product/variations_list.html
{% extends "product/base.html" %}


{% block content %}
<table class='table'>
{% for object in object_list %}
<tr>
<td>
<a href='{{ object.get_absolute_url }}'>{{ object.title }}</a></td><td>{{ object.inventory}}</td>
</td>
</tr>
{% endfor %}
<table>


<form method="POST" action="">
{% csrf_token %}

{{ formset.management_form }}

{% for form in formset %}
{{ form.instance.product.title }}
{{ form.instance.title }}
{{ form.as_p }}


{% endfor %}
<input type="submit" value="Update" class="btn">
</form>



{% endblock %}